//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysorovShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Product
    {

        public int Id { get; set; }
        [Required(ErrorMessage = "Пожалуйста, введите наименование бренда товара!")]
        [Display(Name = "Бренд")]
        public string Brand { get; set; }

        [Required(ErrorMessage = "Пожалуйста, введите наименование модели товара!")]
        [Display(Name = "Модель")]
        public string Model { get; set; }


        [Required(ErrorMessage = "Пожалуйста, введите описание товара!")]
        [Display(Name = "Описание")]
        public string Description { get; set; }

        //[Required(ErrorMessage = "Пожалуйста, добавьте новое изображение товара!")]
        public string Image { get; set; }

        //[Required]
        [Required(ErrorMessage = "Пожалуйста, введите положительное значение цены!")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Пожалуйста, введите положительное значение цены!")]
        [Display(Name = "Цена")]
        public int Price { get; set; }

        //[Required(ErrorMessage = "Пожалуйста, выберите категорию товара!")]
        [RegularExpression(@"[A-Za-z1-9.-]", ErrorMessage = "Пожалуйста, выберите категорию товара!")]
        public Nullable<int> CategoryId { get; set; }


        public Nullable<int> Power { get; set; }
        public Nullable<int> DiskDiameter { get; set; }
        public Nullable<double> DiameterHole { get; set; }
        public Nullable<int> Revs { get; set; }
        public Nullable<int> MainsVoltage { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> MaximumImpact { get; set; }
        public Nullable<int> NoiseLevel { get; set; }
        public string Dimensions { get; set; }

        //[Required(ErrorMessage = "Пожалуйста, добавьте изображение товара!")]
        public byte[] ImageData { get; set; }

        //[Required(ErrorMessage = "Пожалуйста, добавьте новое изображение товара!")]
        public string ImageMimeType { get; set; }

        public IEnumerable<Product> Products { get; set; }
        public SelectList Categories { get; set; }

        public virtual Category Category { get; set; }
    }
}
